### ISSUE TITLE
Program freezes

### ISSUE THREAD

**Issue by scbhatia** [gvikram31/EC500#7]
The program inconsistently freezes, even with a small number of images being downloaded.

**Comment by gvikram31** [comment]
I included "wait_time_limit = True" in the code because it enables "blocking when running out of calls": using the argument wait_on_rate_limit you can have the tweepy wait when running out of calls. By monitoring the HTTP headers returned from Twitter, tweepy now knows exactly how long to wait until the next lump of API calls is available. This is useful when you need more than the number of calls allowed by the rate limit, but don't want your program to fail with an exception or lose track of the current position in your results. 

Twitter sets limits on the number of API calls which means we can't run this program many number of times in a short period. And this problem exists with tweepy also. 

I am looking to resolve this. Will update if I find a solution.
